Algoritmo "numeros_impares_1_a_1000"
// Disciplina   : [Infoirmatica]
// Professor   : Cuinhane
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Pelembe, Jaime Fernando
// Data atual  : 16/05/2023
Var
// Seção de Declarações das variáveis 
i:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
  escreva("Números impares de 1 a 1000")
  
  para i de 1 ate 1000 passo 2 faca
  escreval(i)
  fimpara

Fimalgoritmo